### ISSUE TITLE
blank (black?) image with DirectX 12

### ISSUE THREAD

**Issue by mallochine** [bryal/dxgcap-rs#6]

**Comment by bryal** [comment]
Could you please expand on your issue?
What is the context, i.e. what are you doing. What is the expected behaviour. What actually happens.

There exists a known problem where full-screen DirectX applications are opened in protected mode per default. The DXGI desktop duplication API respects this flag, and as such we can't capture the screen in this context.

If this is your problem, I'm afraid I don't know of any fix, except for making use of dll injection á la Fraps. This, however, is outside the scope of what I want to implement in this software. If someone else wants to implement this kind of functionality, I'd probably have no objections to merging it in.
